create table chess_games(
    id                    serial    primary key,
--    black                 text      not null,
--    black_elo             real      not null,
--    black_rating_diff     real      not null,
--    date_played           date      not null,
--    opening_played        text      not null,
    event_type            text      not null,
    result                text      not null,
    round                 text              ,
    game_link             text      not null,
    termination           text      not null,
--    time_control          text      not null,
--    utc_date_played       date      not null,
--    time_played           time      not null,
    chess_variant         text      not null,
--    white                 text      not null,
--    white_elo             real      not null,
--    white_rating_diff     real      not null,
    black_elo_tentative   text      not null,
    white_elo_tentative   text      not null,
    player                text      not null,
    opponent              text      not null,
    player_color          text      not null,
    opponent_color        text      not null,
    player_rating_diff    real      not null,
    opponent_rating_diff  real      not null,
    player_result         text      not null,
    opponent_result       text      not null,
    time_control_category text      not null,
    datetime_played       timestamp not null,
    starting_time         integer   not null,
    increment             integer   not null,
    in_arena              text      not null,
    rated_casual          text      not null,
    player_rating         real      not null,
    opponent_rating       real      not null
);