version: "3"

x-chess-pipeline-service: &chess-pipeline-service
  restart: no
  depends_on:
    - luigi_server
    - postgres
    - valkey
  volumes:
    - chess_pipeline_logs:/logs
    - .luigi_env:/app/luigi.cfg

services:
  chess_pipeline:
    <<: *chess-pipeline-service
    container_name: chess_pipeline
    image: chess-pipeline

  chess_pipeline_dev:
    <<: *chess-pipeline-service
    container_name: chess_pipeline_dev
    image: chess-pipeline-dev

  luigi_server:
    image: ghcr.io/guidopetri/luigi-server:master
    container_name: luigi_server
    restart: always
    depends_on:
      - postgres
    ports:
      - "127.0.0.1:8082:8082"
    env_file:
      - .luigi_env

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: always
    ports:
      - "127.0.0.1:5432:5432"
    env_file:
      - .postgres_env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db:/sql_scripts:ro
      - ./db/initdb:/docker-entrypoint-initdb.d:ro

  valkey:
    image: valkey/valkey:alpine
    container_name: valkey
    restart: always
    ports:
      - "127.0.0.1:6379:6379"

volumes:
  chess_pipeline_logs:
  postgres_data:
