version: "3"

x-chess-pipeline-service: &chess-pipeline-service
  restart: no
  depends_on:
    - chess_pipeline_postgres
    - valkey
  volumes:
    - chess_pipeline_logs:/logs
  networks:
    - mainnetwork

services:
  chess_pipeline:
    <<: *chess-pipeline-service
    container_name: chess_pipeline
    image: chess-pipeline

  chess_pipeline_dev:
    <<: *chess-pipeline-service
    container_name: chess_pipeline_dev
    image: chess-pipeline-dev

  chess_pipeline_postgres:
    image: postgres:16-alpine
    container_name: chess_pipeline_postgres
    restart: always
    ports:
      - "127.0.0.1:5432:5432"
    env_file:
      - .postgres_env
    networks:
      - mainnetwork
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db:/sql_scripts:ro
      - ./db/initdb:/docker-entrypoint-initdb.d:ro

  valkey:
    image: valkey/valkey:alpine
    container_name: valkey
    restart: always
    networks:
      - mainnetwork
    ports:
      - "127.0.0.1:6379:6379"

volumes:
  chess_pipeline_logs:
  postgres_data:

networks:
  mainnetwork:
    external: true
